# Generated by Django 4.2.11 on 2024-05-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motel_meo', '0002_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
