# Generated by Django 4.2.11 on 2024-05-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motel_meo', '0004_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='person',
            field=models.IntegerField(default=1),
        ),
    ]
